# Theme------------------------------------------
theme_mocha = {
    "background": "#1e1e2e",
    "foreground": "#cdd6f4",
    "rosewater":  "#f5e0dc",
    "flamingo":   "#f2cdcd",
    "pink":       "#f5c2e7",
    "mauve":      "#8839ef",
    "red":        "#f38ba8",
    "maroon":     "#eba0ac",
    "peach":      "#fab387",
    "yellow":     "#f9e2af",
    "green":      "#a6e3a1",
    "teal":       "#94e2d5",
    "sky":        "#89dceb",
    "sapphire":   "#74c7ec",
    "blue":       "#89b4fa",
    "lavender":   "#b4befe",
    "text":       "#cdd6f4",
    "overlay0":   "#6c7086",

}

theme = {
    "background": "#303446",
    "foreground": "#c6d0f5",
    "rosewater":  "#f2d5cf",
    "flamingo":   "#eebebe",
    "pink":       "#f4b8e4",
    "mauve":      "#ca9ee6",
    "red":        "#e78284",
    "maroon":     "#ea999c",
    "peach":      "#ef9f76",
    "yellow":     "#e5c890",
    "green":      "#a6d189",
    "teal":       "#81c8be",
    "sky":        "#99d1db",
    "sapphire":   "#85c1dc",
    "blue":       "#8caaee",
    "lavender":   "#babbf1",
    "text":       "#c6d0f5",
    "overlay0":   "#737994",
    }

theme_latte = {
    "background": "#eff1f5",
    "foreground": "#4c4f69",
    "rosewater":  "#dc8a78",
    "flamingo":   "#dd7878",
    "pink":       "#ea76cb",
    "mauve":      "#8839ef",
    "red":        "#d20f39",
    "maroon":     "#e64553",
    "peach":      "#fe640b",
    "yellow":     "#df8e1d",
    "green":      "#40a02b",
    "teal":       "#179299",
    "sky":        "#04a5e5",
    "sapphire":   "#209fb5",
    "blue":       "#1e66f5",
    "lavender":   "#7287fd",
    "text":       "#4c4f69",
    "overlay0":   "#9ca0b0",
    }
#------------------------------------------------

