#!/bin/bash
while read -r file
do
    case "$1" in
    "d")
        mv "$file" ~/.local/share/Trash/files ;;
	"D")
		rm -f "$file" ;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"bar")
		convert -flop "$file" "$file" ;;
	"underscore")
		convert -flip "$file" "$file" ;;
    "n")
        printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard ;;
    "y")
        xclip -selection clipboard -target image/png "$file" ;;
    esac
done
