# Autocompletion-------------------------------
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS} 
#----------------------------------------------

# Git settings----------------------------------
autoload -Uz vcs_info
precmd() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git:*' formats ' %b '
#-----------------------------------------------

# Other settings--------------------------------
setopt autocd beep nomatch
# Enable colors
autoload -Uz colors && colors
#-----------------------------------------------

# Source---------------------------------------------
# Source zsh files
source $ZDOTDIR/prompt.zsh
source $ZDOTDIR/history.zsh
source $ZDOTDIR/functions.zsh
source $ZDOTDIR/aliases.zsh
source $ZDOTDIR/keybinds.zsh
source $ZDOTDIR/ls-colors.zsh

# Source zsh plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh 2>/dev/null

# Source fzf keybindings
source /usr/share/fzf/key-bindings.zsh 2>/dev/null
source /usr/share/fzf/completion.zsh 2>/dev/null
#------------------------------------------------------

# Export $PATH variables-------------------------------
export PATH=$PATH:$HOME/.config
export PATH=$PATH:$HOME/dots/scripts
#------------------------------------------------------
